import subprocess
import os

GENES = {
    "wbeT": "ATGAAAATATTGTTTCCAGGTGGTTTATCAAGTGAAGCGATAGCACGAATTTTAGGTAATTATAATAACACTATTAGCATGTTTAGTGTAGAAGTAGATAGTTTATTAGTTGGTGAAGCGGAAATTCGTCCGTTAGCAGAAGAATTATCAGGTTTATTTACATTTATTAGTGAA",
    "ctxB": "ATGATTAAATTAAAATTTGGTGTTTTTTTTACAGTTTTACTATCTTCAGCATATGCACATGGAACACCTCAAAATATTACTGATTTGTGTGCAGAATACCACAACACACAAATACATACGCTAAATGATAAGATATTTTCGTATACAGAATCTCTAGCTGGAAAAAGAGAGATGGCTATCATTACTTTTAAGAACGGTGCAACTTTTCAAGTAGAAGTACCAGGTAGTCAACATATAGATTCACAAAAAAAGCGATTGAATTATGGCATTATTCGCAAAACTTC",
    "tcpA": "ATGTTCAAAATTCAAAAAAAGTTTATCGCTACTACTGCATCTGTAGCATTATCTGGTGTAGTAACACCAGGCATAAACCCTAGCGCTAACACTGAAAATTTTTACTTAGCAAGTGTAAGTATTAACGGGGTTAATGACCCTATTACTGCTGTAGCTGTATTAGCAGGACCTAACTTAGATCCAACTACTGGTCAAGTATTACTAGGTGGTAACCAAAGTGCAAATAAGATTATTTGTGAAAAAACTACAAAAGGATTTATTGGCGACTCTAAAGTATATACTGAAATTGAACTGATTTTCGGCATTAACAATAATGCCGTCCAATTATCT",
    "gyrA": "ATGAGCGTGGTTGTAAATCGTGCCCTGCCAGATGTGCGTGATGGTTTAAAACCTGTACATCGTCGTATTCTTTATGCAATGAATGAACTAGGTCTAACTAGTGATAAACCATATAAAAAATCCGCTCGCGTTGTTGGTGAAGTTATTGGTAAATACCACCCACACGGTGACTCAGCAGTTTACGAAGCTATGGTTCGTATGGCACAAAACTTCTCATACCGTTATATGCTGGTTGATGGT",
    "parC": "ATGAGCGAAATTATTTTGGATCGTACTTTAGAACCAGTAAAGCCAGAAGATGTACGTGATGGTCTAAAACCAGTTCATCGTCGTATCTTATACGCAATGAACGAACTAGGCATGACAAGTGATAAACCTTATAAAAAATCAGCTCGTATTGTAGGTGAAGTAATTGGTAAGTACCACCCACACGGTGACTCAGCAGTG",
    "parE": "ATGTCAAAATTACACAAACAATATCGCCACTCAAACTCGATAAGACGAGAGAATGCCGATTGATTTATGTGAAACCGTAGCATCCAAGATTAGGACGCATTGTCAGCTAATAGGTGATTAACCTGAACTATCGCAAGATAGTAGAAAGCTAAATTTTTATTAACTGCGAACATAAGCTGAGTATACATTACCTGACCTATCAATAAGATGGGACAGCTCCTCACTGCTCATTGGTTCACAACTGGCTAAACCAGTGCCGGGCATTATACCGATCACAGTTTCAGTTGCAAGGTATGTTTGAAAAATAAACGGAATTAAATCTCTGTTAACGATAACGTCACTGGAGTGTTTATGCATGCGCCAAACAATCACGACCGCTAAATGCCGTGGTTTAGGGATGATAAGAAAAACGGGCACTCTCAAGTGCCCGTTTACGATGATGGAATGATTGAACTTACCGATTCGCCATACGCTGGCGTACTGCT",
    "scrABC": "ATGTCAAACTTTATTAGCATTGCAGCAACTGGTGGTATCGCTGGTATCGAAATGGCAGGTACTTTAGCAGAAGGTGTACGTG",
    "lip": "ATGAAGAAATTAATCATTTTGTTATTTGCCGCATTGTTGGCAGCAAGTGCTTTCGCTCAACAAGAAGCATTAGAAGGTGG",
    "rbm": "ATGAAAAAACTATTACTTGCCGTAGCACTA",
    "katB": "ATGTCAAACCAAAACGATATTGCTAATATCGCTGACCGTCTTGATGAACAAATTCGTGAAGCAACTGAAAAAGAGCATTTTAA",
    "ahpC": "ATGTCATTAATTAAACCAGCTCCAAACTTCGCAAACCGTGCTGTAGTTTGTGACTTCGAAGCCGAAGCAGGTTGGCAAGAAGC",
    "hapR": "ATGAAAAAATTAGGAGTAACGTCATTCCAACAAAATATTCAGCAAGTCATCGAAAAAATTGATCGCCAAGAACTAGAACTCATTCGTGAAGAAGCCTTTGCAAAACTAAGTGAACATCAAATCTCTCAAGCGCTTAACTTCGAACGCGGTAGCGTTTATTCGGCGAAACTAAAAAACTCAACTGAACTATTCCACCTAGTGATGCACGGTATCAATATTAAGGACTTCATTGAAATTATTGTCGGTTACATTACTCATGTAGAAGCCATTGCAATCTCTCAAGCGCTTAACTTCGAACGCGGTAGCGTTTATTCGGCGAAACTAAAAAACTCAACTGAACTATTCCACCTAGTGATGCACGGTATCAATATTAAGGACTTCATTGAAATTATT"
}

REF = "data/references/2010EL-1786.fasta"

def find_coords():
    with open("query.fasta", "w") as f:
        for name, seq in GENES.items():
            f.write(f">{name}\n{seq}\n")
    
    # Use task blastn-short for short queries
    cmd = [
        "blastn", "-query", "query.fasta", "-db", REF,
        "-outfmt", "6 qseqid sseqid sstart send pident length evalue", "-perc_identity", "50",
        "-task", "blastn-short"
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    
    hits = {}
    for line in res.stdout.strip().split("\n"):
        if not line: continue
        parts = line.split("\t")
        gene = parts[0]
        length = int(parts[5])
        pident = float(parts[4])
        
        # Priority: Length then Identity
        if gene not in hits or length > hits[gene][5] or (length == hits[gene][5] and pident > hits[gene][4]):
            hits[gene] = [parts[0], parts[1], int(parts[2]), int(parts[3]), pident, length, parts[6]]

    print("Gene\tChrom\tStart\tEnd\tIdentity\tLength\tE-value")
    for gene in sorted(hits.keys()):
        h = hits[gene]
        print(f"{h[0]}\t{h[1]}\t{h[2]}\t{h[3]}\t{h[4]}\t{h[5]}\t{h[6]}")

if __name__ == "__main__":
    find_coords()
